name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '.github/workflows/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get version from plugin.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'

      - run: echo "Version is ${{ steps.version.outputs.prop }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./lib
          zip -r WebsiteOpener.zip . \
            -x '*.git*' \
            -x '*.github/*' \
            -x '*.idea/*' \
            -x '__pycache__/*' \
            -x '*.DS_Store'

      - name: Delete existing tag if exists
        run: |
          git tag -d v${{ steps.version.outputs.prop }} || true
          git push origin :refs/tags/v${{ steps.version.outputs.prop }} || true

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'WebsiteOpener.zip'
          tag_name: "v${{ steps.version.outputs.prop }}"
          name: "WebsiteOpener v${{ steps.version.outputs.prop }}"
          body: "Auto release by GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
